(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const c2=$('#canvas2d'),c3=$('#canvas3d'),x2=c2.getContext('2d'),x3=c3.getContext('2d');
const state={models:[],polys:[],layers:new Map(),bounds:null,view:'2d',grid:true,allLayers:true,surface:null,surfaceOn:true,opacity:.76,exag:2,
  v2:{scale:1,ox:0,oy:0},v3:{yaw:-.7,pitch:.78,zoom:1,ox:0,oy:0},drag:null};
const colors=['#c8783f','#1d7565','#517db0','#b85857','#8a6ab2','#77964e','#a56f33','#337b92'];

function parseDXF(text,name){
  const raw=text.replace(/\r/g,'').split('\n'),pairs=[];
  for(let i=0;i+1<raw.length;i+=2)pairs.push([+raw[i].trim(),raw[i+1].trim()]);
  let acadver='Desconocido';for(let i=0;i<pairs.length-1;i++)if(pairs[i][0]===9&&pairs[i][1]==='$ACADVER'){acadver=pairs[i+1][1];break}
  let section='',current=null,poly=null;const polys=[];let unsupported=0;
  const num=v=>{const n=parseFloat(v);return Number.isFinite(n)?n:0};
  function val(ent,code,def=0){const p=ent.data.find(q=>q[0]===code);return p?num(p[1]):def}
  function str(ent,code,def='0'){const p=ent.data.find(q=>q[0]===code);return p?p[1]:def}
  function finish(ent){if(!ent||section!=='ENTITIES')return;const t=ent.type,d=ent.data,layer=str(ent,8);
    if(t==='POLYLINE'){if(poly?.points.length>1)polys.push(poly);poly={layer,points:[],closed:(val(ent,70)&1)!==0};return}
    if(t==='VERTEX'&&poly){poly.points.push({x:val(ent,10),y:val(ent,20),z:val(ent,30)});return}
    if(t==='SEQEND'){if(poly?.points.length>1)polys.push(poly);poly=null;return}
    if(t==='LWPOLYLINE'){const pts=[];let p=null,elev=val(ent,38);for(const q of d){if(q[0]===10){if(p)pts.push(p);p={x:num(q[1]),y:0,z:elev}}else if(q[0]===20&&p)p.y=num(q[1]);else if(q[0]===30&&p)p.z=num(q[1])}if(p)pts.push(p);if(pts.length>1)polys.push({layer,points:pts,closed:(val(ent,70)&1)!==0});return}
    if(t==='LINE'){polys.push({layer,points:[{x:val(ent,10),y:val(ent,20),z:val(ent,30)},{x:val(ent,11),y:val(ent,21),z:val(ent,31)}]});return}
    if(t==='3DFACE'){const pts=[];for(let k=0;k<4;k++)pts.push({x:val(ent,10+k),y:val(ent,20+k),z:val(ent,30+k)});polys.push({layer,points:pts,closed:true});return}
    if(t==='CIRCLE'||t==='ARC'){const cx=val(ent,10),cy=val(ent,20),z=val(ent,30),r=val(ent,40),a0=t==='ARC'?val(ent,50)*Math.PI/180:0,a1=t==='ARC'?val(ent,51)*Math.PI/180:Math.PI*2,span=(a1<a0?a1+Math.PI*2:a1)-a0,pts=[];for(let k=0;k<=32;k++){let a=a0+span*k/32;pts.push({x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r,z})}polys.push({layer,points:pts,closed:t==='CIRCLE'});return}
    if(t==='POINT')polys.push({layer,points:[{x:val(ent,10),y:val(ent,20),z:val(ent,30)}],point:true});
    else if(!['INSERT','TEXT','MTEXT','HATCH','SPLINE'].includes(t))unsupported++;
  }
  for(let i=0;i<pairs.length;i++){const [code,v]=pairs[i];if(code===0){finish(current);current={type:v,data:[]};if(v==='SECTION'&&pairs[i+1]?.[0]===2)section=pairs[i+1][1];else if(v==='ENDSEC')section=''}else current?.data.push([code,v])}finish(current);if(poly?.points.length>1)polys.push(poly);
  if(!polys.length)throw new Error('No se encontraron entidades geométricas compatibles.');
  const years={AC1009:'R12',AC1012:'R13',AC1014:'R14',AC1015:'2000',AC1018:'2004',AC1021:'2007',AC1024:'2010',AC1027:'2013',AC1032:'2018'};
  return{name,polys,unsupported,acadver,version:years[acadver]||acadver};
}

function rebuild(){
  state.polys=state.models.flatMap(m=>m.polys.map(p=>({...p,file:m.name})));
  state.layers.clear();let xmin=Infinity,ymin=Infinity,zmin=Infinity,xmax=-Infinity,ymax=-Infinity,zmax=-Infinity,verts=0;
  for(const p of state.polys){if(!state.layers.has(p.layer))state.layers.set(p.layer,{visible:true,count:0,color:colors[state.layers.size%colors.length]});const l=state.layers.get(p.layer);l.count++;for(const q of p.points){xmin=Math.min(xmin,q.x);xmax=Math.max(xmax,q.x);ymin=Math.min(ymin,q.y);ymax=Math.max(ymax,q.y);zmin=Math.min(zmin,q.z);zmax=Math.max(zmax,q.z);verts++}}
  state.bounds={xmin,xmax,ymin,ymax,zmin,zmax,w:xmax-xmin,h:ymax-ymin,d:zmax-zmin,cx:(xmin+xmax)/2,cy:(ymin+ymax)/2};
  state.surface=null;renderSidebar(verts);$('#welcome').hidden=true;$('#legend').hidden=false;resize();fit();generateSurface();requestAnimationFrame(()=>{resize();fit();draw()});toast(`${state.models.length} archivo${state.models.length>1?'s':''} cargado${state.models.length>1?'s':''}`);
}
function renderSidebar(verts){const b=state.bounds;$('#modelInfo').classList.remove('is-empty');$('#emptyMessage').hidden=true;$('#stats').hidden=false;$('#fileCount').textContent=`${state.models.length} archivo${state.models.length!==1?'s':''}`;$('#entityCount').textContent=state.polys.length.toLocaleString('es-CL');$('#vertexCount').textContent=verts.toLocaleString('es-CL');$('#areaSize').textContent=`${fmt(b.w)} × ${fmt(b.h)} m`;$('#elevationRange').textContent=`${fmt(b.zmin)}—${fmt(b.zmax)} m`;$('#formatVersion').textContent=[...new Set(state.models.map(m=>m.version))].join(' / ');$('#legend span:first-child').textContent=`${fmt(b.zmin)} m`;$('#legend span:last-child').textContent=`${fmt(b.zmax)} m`;
  $('#layers').innerHTML=[...state.layers].map(([n,l],i)=>`<label class="layer"><input type="checkbox" data-layer="${esc(n)}" checked><i class="layer-dot" style="background:${l.color};color:${l.color}"></i><span title="${esc(n)}">${esc(n)}</span><em>${l.count}</em></label>`).join('');
  $$('#layers input').forEach(el=>el.onchange=()=>{state.layers.get(el.dataset.layer).visible=el.checked;draw()});
}
function generateSurface(){if(!state.bounds)return;const b=state.bounds,samples=[];for(const p of state.polys)for(const q of p.points)if(Number.isFinite(q.z)&&q.z!==0)samples.push(q);if(samples.length<3||b.d===0){state.surface=[];draw();return}const n=36,nodes=[];
  for(let j=0;j<n;j++){for(let i=0;i<n;i++){const x=b.xmin+b.w*i/(n-1),y=b.ymin+b.h*j/(n-1);let nearest=[];for(const p of samples){const d=(p.x-x)**2+(p.y-y)**2;if(nearest.length<7){nearest.push([d,p.z]);nearest.sort((a,c)=>a[0]-c[0])}else if(d<nearest[6][0]){nearest[6]=[d,p.z];nearest.sort((a,c)=>a[0]-c[0])}}let sw=0,sz=0;for(const [d,z] of nearest){const w=1/(d+0.0001);sw+=w;sz+=w*z}nodes.push({x,y,z:sz/sw})}}
  const tris=[];for(let j=0;j<n-1;j++)for(let i=0;i<n-1;i++){let a=nodes[j*n+i],bb=nodes[j*n+i+1],c=nodes[(j+1)*n+i],d=nodes[(j+1)*n+i+1];tris.push([a,bb,d],[a,d,c])}state.surface=tris;draw();
}
function resize(){for(const c of[c2,c3]){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(c.width!==r.width*d||c.height!==r.height*d){c.width=r.width*d;c.height=r.height*d;c.getContext('2d').setTransform(d,0,0,d,0,0)}}draw()}
function fit(){if(!state.bounds)return;const c=state.view==='2d'?c2:c3,r=c.getBoundingClientRect(),b=state.bounds;if(state.view==='2d'){state.v2.scale=.86*Math.min(r.width/b.w,r.height/b.h);state.v2.ox=r.width/2;state.v2.oy=r.height/2}else{state.v3.zoom=.9;state.v3.ox=0;state.v3.oy=0}draw()}
function visible(p){return state.layers.get(p.layer)?.visible!==false}
function draw(){if(!state.bounds)return;state.view==='2d'?draw2D():draw3D()}
function grid2D(ctx,w,h,v,b){if(!state.grid)return;let target=90/v.scale,pow=10**Math.floor(Math.log10(target)),step=[1,2,5,10].find(k=>k*pow>=target)*pow;ctx.strokeStyle='#dfe7e2';ctx.lineWidth=1;ctx.beginPath();let x0=Math.ceil(b.xmin/step)*step;for(let x=x0;x<=b.xmax;x+=step){let sx=v.ox+(x-b.cx)*v.scale;ctx.moveTo(sx,0);ctx.lineTo(sx,h)}let y0=Math.ceil(b.ymin/step)*step;for(let y=y0;y<=b.ymax;y+=step){let sy=v.oy-(y-b.cy)*v.scale;ctx.moveTo(0,sy);ctx.lineTo(w,sy)}ctx.stroke()}
function draw2D(){const r=c2.getBoundingClientRect(),w=r.width,h=r.height,b=state.bounds,v=state.v2;x2.clearRect(0,0,w,h);x2.fillStyle='#f4f7f4';x2.fillRect(0,0,w,h);grid2D(x2,w,h,v,b);x2.lineJoin='round';x2.lineCap='round';for(const p of state.polys){if(!visible(p))continue;const l=state.layers.get(p.layer);x2.strokeStyle=l.color;x2.fillStyle=l.color;x2.globalAlpha=.92;x2.lineWidth=Math.max(.65,Math.min(1.8,v.scale*.22));x2.beginPath();p.points.forEach((q,i)=>{let x=v.ox+(q.x-b.cx)*v.scale,y=v.oy-(q.y-b.cy)*v.scale;i?x2.lineTo(x,y):x2.moveTo(x,y)});if(p.closed)x2.closePath();p.point?x2.fillRect(v.ox+(p.points[0].x-b.cx)*v.scale-2,v.oy-(p.points[0].y-b.cy)*v.scale-2,4,4):x2.stroke()}x2.globalAlpha=1;scaleBar(x2,w,h,v.scale)}
function project(q,w,h){const b=state.bounds,v=state.v3,s=Math.max(b.w,b.h),x=(q.x-b.cx)/s,y=(q.y-b.cy)/s,z=((q.z-b.zmin)/(s||1))*state.exag;const cy=Math.cos(v.yaw),sy=Math.sin(v.yaw),cp=Math.cos(v.pitch),sp=Math.sin(v.pitch),x1=x*cy-y*sy,y1=x*sy+y*cy,y2=y1*cp-z*sp,z2=y1*sp+z*cp,cam=2.3,fac=(Math.min(w,h)*1.42*v.zoom)/(cam-y2);return{x:w/2+v.ox+x1*fac,y:h*.58+v.oy-z2*fac,d:y2,z:q.z}}
function draw3D(){const r=c3.getBoundingClientRect(),w=r.width,h=r.height,b=state.bounds;x3.clearRect(0,0,w,h);let grd=x3.createLinearGradient(0,0,0,h);grd.addColorStop(0,'#f9fbfa');grd.addColorStop(1,'#e9f0ec');x3.fillStyle=grd;x3.fillRect(0,0,w,h);
  if(state.grid){x3.strokeStyle='#d7e1dc';x3.lineWidth=.7;for(let i=0;i<=10;i++){let t=i/10,a=project({x:b.xmin+b.w*t,y:b.ymin,z:b.zmin},w,h),bb=project({x:b.xmin+b.w*t,y:b.ymax,z:b.zmin},w,h),c=project({x:b.xmin,y:b.ymin+b.h*t,z:b.zmin},w,h),d=project({x:b.xmax,y:b.ymin+b.h*t,z:b.zmin},w,h);x3.beginPath();x3.moveTo(a.x,a.y);x3.lineTo(bb.x,bb.y);x3.moveTo(c.x,c.y);x3.lineTo(d.x,d.y);x3.stroke()}}
  if(state.surfaceOn&&state.surface?.length){const ts=state.surface.map(t=>{const pp=t.map(q=>project(q,w,h));return{pp,depth:pp.reduce((a,p)=>a+p.d,0)/3,z:t.reduce((a,p)=>a+p.z,0)/3}}).sort((a,c)=>a.depth-c.depth);x3.globalAlpha=state.opacity;for(const t of ts){x3.fillStyle=elevColor((t.z-b.zmin)/(b.d||1));x3.beginPath();x3.moveTo(t.pp[0].x,t.pp[0].y);x3.lineTo(t.pp[1].x,t.pp[1].y);x3.lineTo(t.pp[2].x,t.pp[2].y);x3.closePath();x3.fill()}x3.globalAlpha=1}
  const ps=state.polys.filter(visible).map(p=>({p,depth:p.points.reduce((a,q)=>a+project(q,w,h).d,0)/p.points.length})).sort((a,c)=>a.depth-c.depth);x3.lineJoin='round';for(const item of ps){const p=item.p,l=state.layers.get(p.layer);x3.strokeStyle=l.color;x3.globalAlpha=.9;x3.lineWidth=1.05;x3.beginPath();p.points.forEach((q,i)=>{const s=project(q,w,h);i?x3.lineTo(s.x,s.y):x3.moveTo(s.x,s.y)});if(p.closed)x3.closePath();x3.stroke()}x3.globalAlpha=1}
function elevColor(t){t=Math.max(0,Math.min(1,t));const stops=[[24,79,73],[62,139,108],[176,200,93],[231,168,68],[212,90,61]],p=t*(stops.length-1),i=Math.min(stops.length-2,Math.floor(p)),f=p-i,a=stops[i],b=stops[i+1];return`rgb(${a.map((v,k)=>Math.round(v+(b[k]-v)*f)).join(',')})`}
function scaleBar(ctx,w,h,scale){let target=110/scale,pow=10**Math.floor(Math.log10(target)),m=[1,2,5,10].find(k=>k*pow>=target)*pow,len=m*scale;ctx.fillStyle='#29413a';ctx.fillRect(20,h-28,len,2);ctx.fillRect(20,h-31,1,7);ctx.fillRect(20+len,h-31,1,7);ctx.font='10px system-ui';ctx.fillText(`${fmt(m)} m`,20,h-36)}
function onPointerDown(e){if(!state.bounds)return;state.drag={x:e.clientX,y:e.clientY,ox:state.view==='2d'?state.v2.ox:state.v3.ox,oy:state.view==='2d'?state.v2.oy:state.v3.oy,yaw:state.v3.yaw,pitch:state.v3.pitch,button:e.button};e.currentTarget.setPointerCapture(e.pointerId)}
function onPointerMove(e){if(state.bounds){const r=e.currentTarget.getBoundingClientRect();if(state.view==='2d'){const b=state.bounds,v=state.v2;let x=b.cx+(e.clientX-r.left-v.ox)/v.scale,y=b.cy-(e.clientY-r.top-v.oy)/v.scale;$('#coordinates').textContent=`E ${x.toFixed(1)} · N ${y.toFixed(1)}`}if(state.drag){let dx=e.clientX-state.drag.x,dy=e.clientY-state.drag.y;if(state.view==='2d'||state.drag.button===2){const v=state.view==='2d'?state.v2:state.v3;v.ox=state.drag.ox+dx;v.oy=state.drag.oy+dy}else{state.v3.yaw=state.drag.yaw+dx*.008;state.v3.pitch=Math.max(.12,Math.min(1.48,state.drag.pitch+dy*.006))}draw()}}}
function onWheel(e){if(!state.bounds)return;e.preventDefault();let k=Math.exp(-e.deltaY*.001);if(state.view==='2d'){let r=c2.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,v=state.v2;v.ox=mx-(mx-v.ox)*k;v.oy=my-(my-v.oy)*k;v.scale*=k}else state.v3.zoom=Math.max(.18,Math.min(8,state.v3.zoom*k));draw()}
async function loadFiles(files,replace=false){const fs=[...files].filter(f=>f.name.toLowerCase().endsWith('.dxf'));if(!fs.length)return toast('Seleccione archivos con extensión .dxf',true);try{if(replace)state.models=[];for(const f of fs)state.models.push(parseDXF(await f.text(),f.name));rebuild()}catch(e){toast(`No se pudo abrir: ${e.message}`,true)}}
async function loadDemo(){const key=$('#demoSelect').value,demos={panul:{file:'panul-area3-2018.dxf',name:'Panul · área 3'},navidad:{file:'navidad-area3.dxf',name:'Navidad · área 3'}};const demo=demos[key];try{const embedded=window.DXF_DEMOS?.[key];if(embedded){state.models=[{name:demo.name,version:embedded.version,acadver:embedded.acadver,unsupported:0,polys:embedded.polys.map(p=>({layer:p.l,closed:!!p.c,points:p.p.map(q=>({x:q[0],y:q[1],z:q[2]}))}))}];rebuild();return}const res=await fetch(`assets/${demo.file}`);if(!res.ok)throw 0;state.models=[parseDXF(await res.text(),demo.name)];rebuild()}catch(e){toast(`No se pudo cargar el ejemplo: ${e.message||'archivo no disponible'}`,true)}}
function setView(v){state.view=v;$$('.view-switch button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));c2.hidden=v!=='2d';c3.hidden=v!=='3d';$('#orientation').hidden=v!=='3d';$('#terrainControls').classList.toggle('disabled',v!=='3d');$('#help').textContent=v==='2d'?'Rueda: zoom · Arrastrar: desplazar':'Rueda: zoom · Arrastrar: orbitar · Botón derecho: desplazar';fit()}
function toast(msg,err=false){const t=$('#toast');t.textContent=msg;t.style.background=err?'#7c2e27':'';t.classList.add('show');clearTimeout(t._id);t._id=setTimeout(()=>t.classList.remove('show'),3000)}
function fmt(n){return n.toLocaleString('es-CL',{maximumFractionDigits:1})}function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

$('#openButton').onclick=$('#welcomeOpen').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>loadFiles(e.target.files,true);$('#demoButton').onclick=loadDemo;$$('.view-switch button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#fitButton').onclick=fit;$('#gridButton').onclick=e=>{state.grid=!state.grid;e.currentTarget.classList.toggle('active',state.grid);draw()};$('#surfaceToggle').onchange=e=>{state.surfaceOn=e.target.checked;draw()};$('#exaggeration').oninput=e=>{state.exag=+e.target.value;$('#exaggerationValue').textContent=state.exag.toFixed(1)+'×';draw()};$('#surfaceOpacity').oninput=e=>{state.opacity=+e.target.value;$('#opacityValue').textContent=Math.round(state.opacity*100)+'%';draw()};$('#toggleLayers').onclick=e=>{state.allLayers=!state.allLayers;e.target.textContent=state.allLayers?'Ocultar':'Mostrar';$$('#layers input').forEach(x=>{x.checked=state.allLayers;state.layers.get(x.dataset.layer).visible=state.allLayers});draw()};$('#shotButton').onclick=()=>{const c=state.view==='2d'?c2:c3,a=document.createElement('a');a.download=`terreno-${state.view}.png`;a.href=c.toDataURL('image/png');a.click()};$('#fullscreenButton').onclick=()=>document.fullscreenElement?document.exitFullscreen():$('.workspace').requestFullscreen();
for(const c of[c2,c3]){c.onpointerdown=onPointerDown;c.onpointermove=onPointerMove;c.onpointerup=c.onpointercancel=()=>state.drag=null;c.onwheel=onWheel;c.oncontextmenu=e=>e.preventDefault()}
const dz=$('#dropZone');for(const ev of['dragenter','dragover'])dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('dragging')});for(const ev of['dragleave','drop'])dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('dragging')});dz.addEventListener('drop',e=>loadFiles(e.dataTransfer.files,!e.shiftKey));new ResizeObserver(resize).observe($('.viewport'));setView('2d');
loadDemo();
})();
